INSERT INTO TBL_PRODUCT (PRODUCT_NAME, PRICE)  VALUES ('pneu', 55.00);
INSERT INTO TBL_PRODUCT (PRODUCT_NAME, PRICE)  VALUES ('carrão', 75.00);
INSERT INTO TBL_PRODUCT (PRODUCT_NAME, PRICE)  VALUES ('moto', 45.00);
INSERT INTO TBL_PRODUCT (PRODUCT_NAME, PRICE)  VALUES ('lambreta', 65.00);